version: "3.4"
services:
  ms-configuration:
    image: bakayarusama/ms-configuration:1.0.5
    container_name: ms-configuration
    
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=Debug
        - plateform=windows/amd64
    ports: 
      - 1717:8080
    
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ApplicationVersion: 1.0.0
      ConnectionStrings__Database: "Data Source=/app/Data/database.db"

    volumes:
      - C:\Users\brend\Source\Repos\brendanGiraudet\MS-Configuration\ms-configuration\Data:/app/Data
      
    restart: always